# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60ab33a2d3e0f3353187e9db784ccdfeef8aa109af1c5514730b0b257e2adfdba718d9a0c9cc55269fbe9874ca15d745e0a65fca3f67fb25723512aff8b0ac75

test:
  secret_key_base: 872403469177fa2386510eeca29ac55d2c2a88312753df4134639624fe743ccff19f383daeea06feeb0c1c4b2fc94db769287ea133dbfad40127563e22f72c30

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
